### ISSUE TITLE
Reflection-Free Serialization and Deserialization

### ISSUE THREAD

**Issue by ds5678** [ivaxor/Patreon.NET#2]
Using System.Text.Json source generation would offer performance boosts and enable assembly trimming. Are you amenable to this change? I am willing to contribute it.

Reference: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

**Comment by illja96** [comment]
Please note that right now library is in early stages of development and changes can be very radical.

For now, I don't really see much value in Json performance deserialization uplift because Patreon utilizes pagination and JSON size aren't that big. Despite said, I think this is good optional feature to have. To note, I have never used this feature myself, so I don't know what architectural impact these changes can make. So, I will need some time to try this feature myself. At a first glance it doesn't looks very developer friendly, so I would like this to be implemented as much unobtrusive as possibly because I was designing this library maximizing ease of use and simplicity for non-experienced developers.

If you are willing to help with development of this feature, you can continue discussion here or provide small PoC as draft changes in PR.

**Comment by illja96** [comment]
I was very eager to try this feature, so I have implemented it and pushed PR. It was pretty easy to implement despite a bit overwhelming documentation in first glance. And results are pretty good: 3x faster for first cold start JSON parsing on my PC.
Because this is my first time with this feature, any comments/suggestion are very welcomed @ds5678

**Comment by ds5678** [comment]
Thank you for doing this. I left a comment on your pull request. I didn't notice any other issues.
